apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "fixitpdf.fullname" . }}-dbmigrate-{{ .Release.Revision }}
  labels:
    app: {{ include "fixitpdf.fullname" . }}-dbmigrate
spec:
  backoffLimit: 1
  template:
    metadata:
      labels:
        app: {{ include "fixitpdf.fullname" . }}-dbmigrate
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.worker.image.repository }}:{{ .Values.worker.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        command: ["npm", "run", "migrate", "-w", "packages/shared"]
        args: []
        env:
          - name: APP_TYPE
            value: "dbmigrate"
        envFrom:
          - secretRef:
              name: {{ include "fixitpdf.fullname" . }}
      restartPolicy: {{ .Values.dbMigrationJob.restartPolicy }}
