apiVersion: v1
kind: Secret
metadata:
  name: {{ include "fixitpdf.fullname" . }}
type: Opaque
data:
  {{- range $key, $val := .Values.secrets }}
  {{ $key }}: {{ $val | b64enc | quote }}
  {{- end}}
