name: FixItPDF Manual Publish

on:
  workflow_dispatch:
    inputs:
      sha:
        description: 'Git SHA to deploy'
        required: true
        default: ''

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Install kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: 'v1.21.2'
      id: install

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Set up kubeconfig
      run: |
        aws eks --region ${{ secrets.AWS_REGION }} update-kubeconfig --name shieldgps-k8s-prod

    - name: Helm tool installer
      uses: azure/setup-helm@v3.5

    - name: Create secrets.yaml file
      run: |
        cat <<EOF > secrets.yaml
        secrets:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          REDIS_URL: ${{ secrets.REDIS_URL }}
          APP_AWS_ACCESS_KEY_ID: ${{ secrets.APP_AWS_ACCESS_KEY_ID }}
          APP_AWS_SECRET_ACCESS_KEY: ${{ secrets.APP_AWS_SECRET_ACCESS_KEY }}
          APP_AWS_REGION: ${{ secrets.APP_AWS_REGION }}
          GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
          GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
          APPLE_CLIENT_ID: ${{ secrets.APPLE_CLIENT_ID }}
          APPLE_CLIENT_SECRET: ${{ secrets.APPLE_CLIENT_SECRET }}
          NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}
          STRIPE_SECRET_KEY: ${{ secrets.STRIPE_SECRET_KEY }}
          STRIPE_WEBHOOK_SECRET: ${{ secrets.STRIPE_WEBHOOK_SECRET }}
          RESEND_API_KEY: ${{ secrets.RESEND_API_KEY }}
        EOF

    - name: Deploy with Helm
      run: |
        helm upgrade fixitpdf ./helm \
          -f ./helm/config/config.prod.yaml \
          -f ./secrets.yaml \
          --namespace fixitpdf \
          --set web.image.tag=${{ github.event.inputs.sha }} \
          --set worker.image.tag=${{ github.event.inputs.sha }}

    - name: Cleanup secrets file
      if: always()
      run: rm -f secrets.yaml